#!/usr/bin/env python3

'''deployexecs: find all the executables here, and copy them to a directory you specify'''

import os
import sys
import hashlib

cwd = os.getcwd() # current working directory

executables = []

try:
    dest = sys.argv[1]
except IndexError as e:
    print('Use: deployexecs path/to/destination/directory')
    sys.exit(0)

for item in os.walk(cwd):
    if item[0] == cwd:
        for file in item[2]:
            # various temp file tests...
            if '~' not in file:
                if '#' not in file:
                    if file[0] not in '.':
                        if os.access(file, os.X_OK): # is executable?
                            executables.append(file)

for file in executables:
    os.popen('cp %s %s' % (file, dest))

## New stuff

def hashFile(f):
    '''hashFile(): io.BufferedReader -> Str
    Purpose: read the io.BufferedReader and print its SHA256 hash.
    '''
    hashValue = hashlib.sha256(f)
    return hashValue.hexdigest()

# For each file in target, get hash

# For each file being copied, get hash

# If the thing being copied doesn't exist in the target directory, copy
# it.

# If the thing being copied has the same hash as the file at the
# target, do nothing.

# If the thing being copies has a different hash than the file at the
# target, copy it and say as much.

