#!/usr/bin/env python3

'''deployexecs: find all the executables here, and copy them to a directory you specify'''

import os
import sys

cwd = os.getcwd() # current working directory

executables = []

try:
    dest = sys.argv[1]
except IndexError as e:
    print('Use: deployexecs path/to/destination/directory')
    sys.exit(0)

for item in os.walk(cwd):
    if item[0] == cwd:
        for file in item[2]:
            if '~' not in file:
                if os.access(file, os.X_OK):
                    executables.append(file)

for file in executables:
    os.popen('cp %s %s' % (file, dest))
