#!/usr/bin/env bash

# duh: print output of du in sorted, human-readable format

# Test whether there's a flag and a path
if [ -z $2 ]
then
    path=$1
else
    arg=$1
    path=$2
    #echo 'The args were' $arg $path
fi

# Test whether the -r flag is present. If so,
# reverse order of sort.
if [ -z $arg ]
then
    #echo "No arg found"
    for file in `du $path | sort -n | cut -f 2`; do du -h $file; done
else
    if [[ "$arg" == '-r' ]]
    then
	#echo "The arg -r was found"
	for file in `du $path | sort -nr | cut -f 2`; do du -h $file; done
    else
	#echo "The arg " $arg " was found" 
	for file in `du $path | sort -n | cut -f 2`; do du -h $file; done
    fi
fi

# Run du on the list of files that have been sorted by
# their byte size above.
# for file in $files
# do du -h $file 
# done
