#!/usr/bin/env bash

# epoch2local: Str -> StdOut
# Purpose: take Epoch time in as Str and print a human-readable
#          time to StdOut in system local time.

EPOCH="$1"
FORMAT="+%Y-%m-%dT%T %Z"

if [ `uname` == "Darwin" ]
then
    date -j -f "%s" "$EPOCH" "$FORMAT"
elif [ `uname` == "Linux" ]
then
    date $UTC --date=@"$EPOCH" "$FORMAT"
fi
