#!/usr/bin/env python3

# explodecidr: list all the IP addresses in a CIDR block

import os
import sys
import netaddr # Importing the whole module so I can catch particular Exceptions

def processCidr(cidr):
    '''processCidr: String --> StdOut
    Purpose: find all IP addresses in String-represenation of a CIDR block
             and print to StdOut
    '''
    try:

        # build an IPNetwork object from the cidr
        ips = netaddr.IPNetwork(cidr)

    except netaddr.core.AddrFormatError as e:
        print("Malformed CIDR block: %s" % e)
        return

    for addr in ips:
        print(addr)


## Function calls

if __name__ == '__main__':
    if not os.isatty(0):
        try:
            inputLines = sys.stdin.readlines()
            for line in inputLines:
                # remove newline character from line
                cidr = line.rstrip()
                processCidr(cidr)
        except Exception as e:
            print(e)
            pass
    else:
        try:
            cidr = sys.argv[1]
            processCidr(cidr)
        except Exception as e:
            print(e)
            pass
