#!/bin/bash

# hmv: hyper move
# Purpose: mv a file from <here> to <there-sha256sum>

arg1=$1
arg2=$2

if [ `uname` == "Darwin" ]
then
    SHASUM="shasum 256"
elif [ `uname` == "Linux" ]
then
    SHASUM="sha256sum"
else
    echo "Error -- unsupported platform. Can't tell what SHA utility to use."
    exit
fi


if [ -f $arg1 ]
then
    echo "found a file"
    hash=`$SHASUM $arg1 2>/dev/null | cut -f 1 -d " "`
    extCount=`echo $arg1 | grep -o "\." | wc -l`
    cutField=`echo "$extCount+1" | bc`
    if [ $extCount == 0 ]
    then
	echo "extCount is 0"
	hash=`$SHASUM $arg1 2>/dev/null | cut -f 1 -d " "`
	echo $arg1 $hash	
    else
	newPrefix=`echo $arg1 | cut -f 1-${extCount} -d "."`
	extension=`echo $arg1 | cut -f ${cutField} -d "."`
	echo $arg1 $hash $newPrefix $extension
    fi
else
    echo "error: $arg1 doesn't exist"
fi

