#!/usr/bin/env python3

import netaddr
import sys
import os

def isIP(addr):
    '''isIP: Str1 -> StrA
    Purpose: see if the Str represents an IP address, and return either
             the version of IP it represents, or "No".
    '''
    
    try:
        addr = netaddr.IPAddress(addr.rstrip())
        return("IPv%s" % addr.version)
    except netaddr.core.AddrFormatError as e:
        return("No")
    
if __name__ == '__main__':
    if not os.isatty(0):
        input = sys.stdin.readlines()
        for line in input:
            print(isIP(line))
    else:
        try:
            print(isIP(sys.argv[1]))
        except IndexError as e:
            print('Correct use: nslookupip /path/to/ListOfIPs')
